### ISSUE TITLE
Temporal Checks Fail

### ISSUE THREAD

**Issue by thiloshon** [bd-R/bdchecks#31]
Temporal checks fail as follows:

```
Warning: Error in .local: unused argument (format = "%Y-%m-%d")
  91: lubridate::as_date
  87: function_list[[i]]
  86: freduce
  85: _fseq
  84: eval
  83: eval
  81: %>%
  80: get(paste0("dc_", dc@name))
  79: bdchecks::perform_dc
  78: question$flag_data [/Users/thiloshonnagarajah/RProjects/bdclean/R/reference_classes.R#101]
  77: data_store()[[checks]]$flag_data [/Users/thiloshonnagarajah/RProjects/bdclean/R/reference_classes.R#266]
  73: observeEventHandler [modules/flagging-module.R#62]
   2: shiny::runApp
   1: bdclean_app [/Users/thiloshonnagarajah/RProjects/bdclean/R/run_bdclean.R#17]
```

**Comment by Martis6** [comment]
It's a known issue of lubridate in the 3.4 R, but in 4.0 R and later it works fine (and passes r cmd check).

**Comment by tom-gu** [comment]
@Martis6 @PoGibas @thiloshon 

The fact that:
```r
bdchecks:::dc_eventdate_standard(data_bats$eventDate)
# And
get("dc_eventdate_standard")(unique(data_bats$eventDate))
```
Both are running fine on R(3.6.1) with lubridate(1.7.9), led me to the conclusion that it's not a real `lubridate` bug, but a shapeshifter :shipit: .
Further investigation revealed that it's probably an Evaluation issue.

Replacing:
https://github.com/bd-R/bdchecks/blob/a77373c3162166203dc9368c44dfd9f2bebcccb1/R/dc_eventdate_standard.R#L9

With:
```r
    suppressWarnings() %>% 
    format(format="%Y-%m-%d") %>% 
    lubridate::as_date() %>% 
```

Fixes the issue

**What do you think?**

**Comment by Martis6** [comment]
If we separate them, then it has another issue. Running `perform_test_dc()` fails all temporal checks with "20180202" input
<img width="348" alt="Screenshot 2020-09-17 at 11 22 49" src="https://user-images.githubusercontent.com/30773639/93442545-b74b2100-f8d8-11ea-8881-24cb5d8c90a0.png">

**Comment by thiloshon** [comment]
@Martis6 Lets set lowest version to 4.0

**Comment by thiloshon** [comment]
@Martis6 After fixing this, please validate with this input as well:
[dataset.csv](https://github.com/bd-R/bdchecks/files/6797139/dataset.csv)
