### ISSUE TITLE
Add information about missing/not performed data checks

### ISSUE THREAD

**Issue by PoGibas** [bd-R/bdchecks#5]
Some of the data checks might not be performed (eg., missing target column(s) or missing dependency). Now there's notification to console.  

Add a feature to notify about not performed data checks (pop up message) or additional table in filtering panel.

**Comment by tom-gu** [comment]
Issue moved to [bd-R/bdchecks.app #15](https://github.com/bd-R/bdchecks.app/issues/15) via [**ZenHub**](https://www.zenhub.com/)
